const APP_VERSION='D1-RC2.0.0',DATA_VERSION='PDH-ROUTES-2.0',GEOMETRY_VERSION='PDH-GEOMETRY-1.0';
let routeData={routes:[],summary:{}},geometryBase={nodes:[],summary:{}},currentRouteId=localStorage.getItem('d1-route')||'R-001',view='routes',installPrompt=null,watchId=null,gpsActive=false,fixes=[],lastAccepted=null,lastFix=null,traceSession=null;
const $=id=>document.getElementById(id);
const services=()=>window.DiDauServices||null,domain=()=>window.DiDauRouteGeometry||null,ui=()=>window.DiDauUiShell||null;
const read=(k,d)=>services()?.JsonStore?.read?.(k,d)??(()=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}})();
const write=(k,v)=>services()?.JsonStore?.write?.(k,v)??(localStorage.setItem(k,JSON.stringify(v)),v);
const users=()=>services()?.AccountStore?.users?.()||read('d1-users',[]),session=()=>services()?.AccountStore?.session?.()||read('d1-session',null),setUsers=v=>services()?.AccountStore?.setUsers?.(v)||write('d1-users',v),setSession=v=>services()?.AccountStore?.setSession?.(v)??(v?write('d1-session',v):localStorage.removeItem('d1-session'));
const geometryLocal=()=>services()?.GeometryStore?.overrides?.()||read('d1-geometry-overrides',{}),setGeometryLocal=v=>services()?.GeometryStore?.setOverrides?.(v)||write('d1-geometry-overrides',v),traces=()=>services()?.GeometryStore?.traces?.()||read('d1-segment-traces',{}),setTraces=v=>services()?.GeometryStore?.setTraces?.(v)||write('d1-segment-traces',v),pois=()=>services()?.PoiStore?.all?.()||read('d1-pois',[]),setPois=v=>services()?.PoiStore?.setAll?.(v)||write('d1-pois',v),auditLog=()=>services()?.AuditStore?.all?.()||read('d1-audit',[]);
function audit(action,target,detail={}){if(services()?.AuditStore?.append)return services().AuditStore.append(action,target,detail);const a=auditLog();a.unshift({at:Date.now(),actor:session()?.email||'local',role:session()?.role||'guest',action,target,detail});write('d1-audit',a.slice(0,500));return a[0]}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function syncInstall(){if(isStandalone()){$('installBox')?.classList.add('hidden');return}$('installBox')?.classList.remove('hidden');const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);if($('installMsg'))$('installMsg').textContent=installPrompt?'Thiết bị sẵn sàng cài PWA.':ios?'Safari → Chia sẻ → Thêm vào Màn hình chính.':'Chrome/Edge → menu → Cài ứng dụng.'}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;syncInstall()});addEventListener('appinstalled',()=>{installPrompt=null;syncInstall();audit('APP_INSTALLED','PWA')});
if($('installBtn'))$('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;syncInstall()}else alert($('installMsg')?.textContent||'Thiết bị chưa sẵn sàng cài PWA.')};

// Compatibility facade. Business logic lives in Services / Route-Geometry Domain / UI Shell.
function routeById(id){return domain()?.RouteDomain?.byId?.(id)||routeData.routes.find(r=>r.id===id)||routeData.routes[0]||null}
function selectRoute(id,source='manual'){currentRouteId=id;services()?.RouteStore?.setSelectedId?.(id,source);if(!services()?.RouteStore)localStorage.setItem('d1-route',id);return ui()?.selectRoute?.(id,source)??(updateHero(),render(),id)}
function updateHero(){if(ui()?.updateHero)return ui().updateHero();const r=routeById(currentRouteId);if(!r)return;if($('routeTitle'))$('routeTitle').textContent=`${r.id} · ${r.name}`;if($('routeInfo'))$('routeInfo').textContent=`${r.group||''} · ${(r.segments||[]).length} đoạn`}
function mergedNodes(){return domain()?.GeometryDomain?.mergedNodes?.()||[]}
function geomCounts(){return domain()?.GeometryDomain?.counts?.()||{approved:0,captured:0,pending:0}}
function norm(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function nodeForName(name,approvedOnly=true){return domain()?.GeometryDomain?.nodeForName?.(name,approvedOnly)||null}
function segmentBlocked(s){return domain()?.RouteDomain?.segmentBlocked?.(s)??/CHẶN|KHÔNG DÙNG|TƯƠNG LAI/.test(`${s?.status||''} ${s?.role||''}`)}
function traceFor(id){return domain()?.GeometryDomain?.traceFor?.(id)||traces()[id]||null}
function edgeState(s){return domain()?.GeometryDomain?.edgeState?.(s)||{state:'PENDING_GEOMETRY',reason:'Domain chưa sẵn sàng'}}
function routeState(r){return domain()?.RouteDomain?.state?.(r)||{state:'DRAFT',active:0,eligible:(r?.segments||[]).length,ready:0}}
function qaState(){return domain()?.RouteDomain?.qa?.()||{qa005:'BLOCKED',qa010:'BLOCKED',approved:0,active:0,eligible:0}}
function metrics(){return ui()?.metrics?.()||''}
function tagState(s){return s==='ACTIVE_TRACE'||s==='APPROVED_GEOMETRY'||s==='ACTIVE'?'good':/BLOCKED|PENDING|DRAFT/.test(String(s||''))?'warn':''}
function renderRoutes(q=''){return ui()?.renderRoutes?.(q)}
function renderGeometry(q=''){return ui()?.renderGeometry?.(q)}
function renderLibrary(q=''){return ui()?.renderLibrary?.(q)}
function renderAdmin(){return ui()?.renderAdmin?.()}
function render(){return ui()?.render?.()}
function distanceKm(a,b){return domain()?.geo?.distanceKm?.(a,b)??Infinity}
function pointSegKm(p,a,b){return domain()?.geo?.pointSegKm?.(p,a,b)??Infinity}
function distanceToTrace(f,t){return domain()?.GeometryDomain?.distanceToTrace?.(f,t)??Infinity}
function recognizeRoute(f){return domain()?.GeometryDomain?.recognizeRoute?.(f)||null}

function weightedFix(){if(!fixes.length)return null;let sw=0,lat=0,lng=0,acc=0;for(const f of fixes){const w=1/Math.max(25,f.accuracy*f.accuracy);sw+=w;lat+=f.lat*w;lng+=f.lng*w;acc+=f.accuracy*w}const n=fixes.at(-1);return{...n,lat:lat/sw,lng:lng/sw,accuracy:Math.round(acc/sw)}}
function acceptableFix(f){if(!Number.isFinite(f.lat)||!Number.isFinite(f.lng)||!Number.isFinite(f.accuracy)||f.accuracy>250)return false;if(lastAccepted){const dt=(f.at-lastAccepted.at)/1000;if(dt>0){const kph=distanceKm(lastAccepted,f)/dt*3600,reported=Number.isFinite(f.speed)&&f.speed>=0?f.speed*3.6:null;if(kph>250&&(reported===null||reported<180))return false}}return true}
function quality(a){return a<=25?'RẤT TỐT':a<=50?'TỐT':a<=100?'TRUNG BÌNH':'YẾU'}
function renderFix(f){lastFix=f;if($('gpsStatus'))$('gpsStatus').textContent=`GPS: ${f.lat.toFixed(5)}, ${f.lng.toFixed(5)}`;if($('gpsAccuracy'))$('gpsAccuracy').textContent=`±${f.accuracy} m · ${quality(f.accuracy)}`;if($('gpsMotion'))$('gpsMotion').textContent=`Tốc độ: ${Number.isFinite(f.speed)&&f.speed>=0?Math.round(f.speed*3.6)+' km/h':'—'} · Hướng: ${Number.isFinite(f.heading)&&f.heading>=0?Math.round(f.heading)+'°':'—'}`;if($('gpsAge'))$('gpsAge').textContent=`Tuổi mẫu: ${Math.max(0,Math.round((Date.now()-f.at)/1000))}s`;const rr=recognizeRoute(f);if(!rr){if($('routeDetect'))$('routeDetect').innerHTML='Map matching: <b>chưa có geometry/trace được duyệt</b>.';return}const d=rr.distance<1?Math.round(rr.distance*1000)+' m':rr.distance.toFixed(1)+' km';if($('routeDetect'))$('routeDetect').innerHTML=`${rr.source==='APPROVED_TRACE'?'Đang khớp':'Ứng viên'}: <b>${rr.route.id} · ${rr.segment.id}</b><br>${d} · ${rr.source} · tin cậy <b>${rr.confidence}</b>`;if(rr.source==='APPROVED_TRACE'&&rr.confidence==='CAO'&&currentRouteId!==rr.route.id)selectRoute(rr.route.id,'approved-trace');write('d1-route-detection',{routeId:rr.route.id,segmentId:rr.segment.id,distanceKm:rr.distance,confidence:rr.confidence,source:rr.source,at:Date.now()})}
function appendTracePoint(f){if(!traceSession)return;const pts=traceSession.points,last=pts.at(-1);if(!last||distanceKm(last,f)>=0.01||f.at-last.at>=5000){pts.push({lat:f.lat,lng:f.lng,accuracy:f.accuracy,at:f.at});traceSession.lastAt=f.at;if(pts.length%10===0)render()}}
function onPosition(p){const f={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy||999,speed:p.coords.speed,heading:p.coords.heading,at:p.timestamp||Date.now()};if(!acceptableFix(f)){if($('gpsAccuracy'))$('gpsAccuracy').textContent=`Mẫu loại · ±${Math.round(f.accuracy)} m`;return}lastAccepted=f;fixes.push(f);if(fixes.length>7)fixes.shift();const sm=weightedFix();services()?.GpsStore?.setLast?.(sm)||write('d1-last-gps',sm);renderFix(sm);window.dispatchEvent(new CustomEvent('a1:gps',{detail:sm}));appendTracePoint(sm)}
function onErr(e){const m={1:'chưa cấp quyền vị trí',2:'không lấy được vị trí',3:'hết thời gian chờ'};if($('gpsStatus'))$('gpsStatus').textContent=`GPS: ${m[e.code]||'lỗi '+e.code}`;if($('gpsAccuracy'))$('gpsAccuracy').textContent='Kiểm tra quyền vị trí'}
function startGPS(){if(!navigator.geolocation){alert('Thiết bị không hỗ trợ Geolocation.');return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);gpsActive=true;$('gpsBtn')?.classList.add('on');if($('gpsStatus'))$('gpsStatus').textContent='GPS: đang lấy vị trí…';navigator.geolocation.getCurrentPosition(onPosition,()=>{},{enableHighAccuracy:false,timeout:5000,maximumAge:10000});watchId=navigator.geolocation.watchPosition(onPosition,onErr,{enableHighAccuracy:true,timeout:20000,maximumAge:0});if(navigator.vibrate)navigator.vibrate(25)}
if($('gpsBtn'))$('gpsBtn').onclick=startGPS;

window.captureNode=id=>{if(!lastFix)return alert('Bật GPS và chờ vị trí trước.');if(lastFix.accuracy>80)return alert('Sai số GPS >80 m. Hãy chờ tín hiệu tốt hơn.');const ov=geometryLocal();ov[id]={lat:lastFix.lat,lng:lastFix.lng,accuracy:lastFix.accuracy,capturedAt:Date.now(),capturedBy:session()?.email||'local-loader',status:'FIELD_CAPTURED',approval:'PENDING_ADMIN_APPROVAL'};setGeometryLocal(ov);audit('NODE_CAPTURED',id,{accuracy:lastFix.accuracy});render()};
window.approveNode=id=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');const ov=geometryLocal();if(!ov[id])return;ov[id].status='APPROVED_GEOMETRY';ov[id].approval='APPROVED';ov[id].approvedAt=Date.now();ov[id].approvedBy=session().email;setGeometryLocal(ov);audit('NODE_APPROVED',id,{accuracy:ov[id].accuracy});render();if(lastFix)renderFix(lastFix)};
window.resetNode=id=>{if(session()?.role!=='admin')return;const ov=geometryLocal();delete ov[id];setGeometryLocal(ov);audit('NODE_RESET',id);render()};
window.startTrace=(routeId,segmentId)=>{const route=routeById(routeId),segment=route?.segments?.find(s=>s.id===segmentId);if(!segment||segmentBlocked(segment))return alert('Đoạn này bị chặn theo policy.');if(traceSession)return alert('Đang ghi một đoạn khác. Hãy dừng trước.');if(!gpsActive)startGPS();traceSession={routeId,segmentId,startedAt:Date.now(),points:[]};audit('TRACE_STARTED',segmentId,{routeId});render()};
function traceBanner(){return `<div class="traceon">● ĐANG GHI ${traceSession.segmentId} · ${traceSession.points.length} điểm <button class="btn" onclick="stopTrace()">Dừng & lưu</button> <button class="btn danger" onclick="cancelTrace()">Hủy</button></div>`}
window.stopTrace=()=>{if(!traceSession)return;const t=traces();if(traceSession.points.length<2)return alert('Chưa đủ điểm GPS để tạo trace.');t[traceSession.segmentId]={...traceSession,endedAt:Date.now(),status:'FIELD_TRACE',capturedBy:session()?.email||'local-loader'};setTraces(t);audit('TRACE_CAPTURED',traceSession.segmentId,{points:traceSession.points.length});traceSession=null;render()};
window.cancelTrace=()=>{if(traceSession)audit('TRACE_CANCELLED',traceSession.segmentId,{points:traceSession.points.length});traceSession=null;render()};
window.approveTrace=id=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');const t=traces();if(!t[id])return;t[id].status='APPROVED_TRACE';t[id].approvedAt=Date.now();t[id].approvedBy=session().email;setTraces(t);audit('TRACE_APPROVED',id,{points:t[id].points?.length||0});render();if(lastFix)renderFix(lastFix)};

window.openPoiForm=()=>{$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Thêm địa điểm</h2><input id="poiName" placeholder="Tên địa điểm"><select id="poiCategory"><option>Quán ăn</option><option>Coffee</option><option>Lưu trú</option><option>Trạm dừng</option><option>Cây xăng</option><option>Vui chơi</option><option>Tham quan</option><option>Tâm linh</option></select><input id="poiSub" placeholder="Phân loại phụ"><input id="poiNote" placeholder="Ghi chú"><input id="poiImage" type="file" accept="image/*"><label><input id="poiVerified" type="checkbox" style="width:auto"> Tôi đã kiểm chứng tại chỗ</label><div class="actions"><button class="primary" onclick="savePoi()">Lưu</button><button onclick="closeModal()">Hủy</button></div><p class="meta">Tọa độ sẽ lấy từ GPS hiện tại nếu đang có. Ảnh tối đa 700 KB để bảo vệ bộ nhớ cục bộ.</p></div></div>`};
window.savePoi=async()=>{const name=$('poiName').value.trim();if(!name)return alert('Nhập tên địa điểm.');let image=null,file=$('poiImage').files[0];if(file){if(file.size>700000)return alert('Ảnh vượt 700 KB.');image=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const p={id:'P-'+Date.now(),name,category:$('poiCategory').value,subcategory:$('poiSub').value.trim(),note:$('poiNote').value.trim(),verified:$('poiVerified').checked,lat:lastFix?.lat??null,lng:lastFix?.lng??null,accuracy:lastFix?.accuracy??null,routeId:services()?.RouteStore?.getSelectedId?.()||currentRouteId,image,createdAt:Date.now(),createdBy:session()?.email||'local-user'};const list=pois();list.unshift(p);setPois(list);audit('POI_CREATED',p.id,{routeId:p.routeId,verified:p.verified});closeModal();ui()?.setView?.('library')||render()};
function parseMapUrl(u){try{const d=decodeURIComponent(u);let m=d.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);if(!m)m=d.match(/!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)/);return m?{lat:+m[1],lng:+m[2]}:null}catch{return null}}
window.openShareImport=()=>{$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Nhận link Google Maps</h2><input id="mapUrl" placeholder="Dán link Google Maps đầy đủ"><input id="mapName" placeholder="Tên địa điểm"><button class="primary" onclick="saveMapLink()">Phân tích & lưu</button><p class="meta">Hỗ trợ link có @lat,lng hoặc !3dlat!4dlng. Link rút gọn cần mở ra URL đầy đủ trước.</p></div></div>`};
window.saveMapLink=()=>{const url=$('mapUrl').value.trim(),name=$('mapName').value.trim()||'Điểm chia sẻ Google Maps',c=parseMapUrl(url);if(!c)return alert('Không tìm thấy tọa độ trong link này. Hãy dùng URL đầy đủ.');const list=pois(),p={id:'P-'+Date.now(),name,category:'Chia sẻ Maps',subcategory:'Google Maps',note:url,verified:false,lat:c.lat,lng:c.lng,accuracy:null,routeId:services()?.RouteStore?.getSelectedId?.()||currentRouteId,createdAt:Date.now(),createdBy:session()?.email||'local-user'};list.unshift(p);setPois(list);audit('MAP_LINK_IMPORTED',p.id,{lat:c.lat,lng:c.lng});closeModal();ui()?.setView?.('library')||render()};
function backupObject(){return{schema:1,appVersion:APP_VERSION,createdAt:Date.now(),geometry:geometryLocal(),traces:traces(),pois:pois(),audit:auditLog()}}
window.exportBackup=()=>{const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PDH-D1-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);audit('BACKUP_EXPORTED','local')};
window.importBackup=async file=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');if(!file)return;try{const data=JSON.parse(await file.text());if(data.schema!==1)throw new Error('Sai schema');if(data.geometry)setGeometryLocal(data.geometry);if(data.traces)setTraces(data.traces);if(data.pois)setPois(data.pois);if(Array.isArray(data.audit))services()?.JsonStore?.write?.('d1-audit',data.audit.slice(0,500))||write('d1-audit',data.audit.slice(0,500));audit('BACKUP_IMPORTED',file.name);render()}catch(e){alert('Backup không hợp lệ: '+e.message)}};
window.clearAudit=()=>{if(session()?.role!=='admin')return;if(confirm('Xóa audit log cục bộ?')){services()?.AuditStore?.clear?.()||write('d1-audit',[]);audit('AUDIT_RESET','local');render()}};

async function hash(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
window.openAccount=()=>{const s=session();$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Tài khoản</h2>${s?`<p><b>${s.email}</b> · ${s.role}</p><div class="actions"><button onclick="logout()">Đăng xuất</button></div>`:`<input id="email" type="email" placeholder="Email"><input id="pass" type="password" placeholder="Mật khẩu"><div class="actions"><button class="primary" onclick="login()">Đăng nhập</button><button onclick="createUser()">Tạo User</button><button onclick="createAdmin()">Tạo Admin đầu tiên</button></div>`}<p class="meta">Tài khoản hiện lưu cục bộ trên thiết bị; chưa phải backend authentication đa thiết bị.</p></div></div>`};
window.closeModal=()=>{if($('modal'))$('modal').innerHTML=''};
window.createUser=async()=>{const email=$('email').value.trim().toLowerCase(),pass=$('pass').value;if(!email||pass.length<6)return alert('Email hợp lệ, mật khẩu ≥6 ký tự.');let u=users();if(u.some(x=>x.email===email))return alert('Email đã tồn tại.');u.push({email,passHash:await hash(pass),role:'user'});setUsers(u);setSession({email,role:'user'});audit('USER_CREATED',email);closeModal();render()};
window.createAdmin=async()=>{const email=$('email').value.trim().toLowerCase(),pass=$('pass').value;if(!email||pass.length<6)return alert('Email hợp lệ, mật khẩu ≥6 ký tự.');let u=users();if(u.some(x=>x.role==='admin'))return alert('Thiết bị đã có Admin.');u.push({email,passHash:await hash(pass),role:'admin'});setUsers(u);setSession({email,role:'admin'});audit('ADMIN_CREATED',email);closeModal();render()};
window.login=async()=>{const email=$('email').value.trim().toLowerCase(),ph=await hash($('pass').value),u=users().find(x=>x.email===email&&x.passHash===ph);if(!u)return alert('Sai tài khoản/mật khẩu.');setSession({email:u.email,role:u.role});audit('LOGIN',email,{role:u.role});closeModal();render()};
window.logout=()=>{audit('LOGOUT',session()?.email||'local');setSession(null);closeModal();render()};

async function permissionState(){try{if(!navigator.permissions)return;const s=await navigator.permissions.query({name:'geolocation'});if(s.state==='denied'){if($('gpsStatus'))$('gpsStatus').textContent='GPS: quyền vị trí đang bị chặn';if($('gpsAccuracy'))$('gpsAccuracy').textContent='Mở quyền vị trí trong trình duyệt'}}catch{}}
async function boot(){syncInstall();permissionState();try{const [r,g]=await Promise.all([fetch(`data/routes-pdh.json?v=${DATA_VERSION}`,{cache:'reload'}),fetch(`data/geometry-pdh.json?v=${GEOMETRY_VERSION}`,{cache:'reload'})]);if(!r.ok||!g.ok)throw new Error('HTTP dữ liệu');routeData=await r.json();geometryBase=await g.json();if(routeData.version!==DATA_VERSION||geometryBase.version!==GEOMETRY_VERSION)throw new Error('Sai version dữ liệu');currentRouteId=services()?.RouteStore?.getSelectedId?.()||currentRouteId;if(!routeData.routes.some(x=>x.id===currentRouteId)){currentRouteId='R-001';services()?.RouteStore?.setSelectedId?.('R-001','bootstrap')}const cached=services()?.GpsStore?.last?.()||read('d1-last-gps',null);if(cached&&Date.now()-cached.at<3600000)renderFix(cached);render()}catch(e){if($('main'))$('main').innerHTML=`<div class="panel badbox"><h2>Lỗi nạp dữ liệu</h2><p>${e.message}</p></div>`}}
boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
