const APP_VERSION='D1-RC1.5.0',DATA_VERSION='PDH-ROUTES-2.0',GEOMETRY_VERSION='PDH-GEOMETRY-1.0';
let routeData={routes:[],summary:{}},geometryBase={nodes:[],summary:{}},currentRouteId=localStorage.getItem('d1-route')||'R-001',view='routes',installPrompt=null,watchId=null,gpsActive=false,fixes=[],lastAccepted=null,lastFix=null,traceSession=null;
const $=id=>document.getElementById(id);
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const users=()=>read('d1-users',[]),session=()=>read('d1-session',null),setUsers=v=>write('d1-users',v),setSession=v=>v?write('d1-session',v):localStorage.removeItem('d1-session');
const geometryLocal=()=>read('d1-geometry-overrides',{}),setGeometryLocal=v=>write('d1-geometry-overrides',v),traces=()=>read('d1-segment-traces',{}),setTraces=v=>write('d1-segment-traces',v),pois=()=>read('d1-pois',[]),setPois=v=>write('d1-pois',v),auditLog=()=>read('d1-audit',[]);
function audit(action,target,detail={}){const a=auditLog();a.unshift({at:Date.now(),actor:session()?.email||'local',role:session()?.role||'guest',action,target,detail});write('d1-audit',a.slice(0,500))}
function isStandalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function syncInstall(){if(isStandalone()){$('installBox').classList.add('hidden');return}$('installBox').classList.remove('hidden');const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent);$('installMsg').textContent=installPrompt?'Thiết bị sẵn sàng cài PWA.':ios?'Safari → Chia sẻ → Thêm vào Màn hình chính.':'Chrome/Edge → menu → Cài ứng dụng.'}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;syncInstall()});addEventListener('appinstalled',()=>{installPrompt=null;syncInstall();audit('APP_INSTALLED','PWA')});
$('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;syncInstall()}else alert($('installMsg').textContent)};
function routeById(id){return routeData.routes.find(r=>r.id===id)||routeData.routes[0]}
function selectRoute(id,source='manual'){currentRouteId=id;localStorage.setItem('d1-route',id);localStorage.setItem('d1-route-source',source);updateHero();render()}
function updateHero(){const r=routeById(currentRouteId);if(!r)return;$('routeTitle').textContent=`${r.id} · ${r.name}`;const rs=routeState(r);$('routeInfo').textContent=`${r.group} · ${r.segments.length} đoạn · ${rs.state}`}
function mergedNodes(){const ov=geometryLocal();return geometryBase.nodes.map(n=>({...n,lat:null,lng:null,accuracy:null,status:'PENDING_COORDINATE',approval:'PENDING_ADMIN_APPROVAL',...(ov[n.id]||{})}))}
function geomCounts(){const n=mergedNodes();return{approved:n.filter(x=>x.status==='APPROVED_GEOMETRY').length,captured:n.filter(x=>x.status==='FIELD_CAPTURED').length,pending:n.filter(x=>x.status==='PENDING_COORDINATE').length}}
function norm(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function nodeForName(name,approvedOnly=true){const key=norm(name),list=mergedNodes().filter(n=>!approvedOnly||n.status==='APPROVED_GEOMETRY');return list.find(n=>norm(n.name)===key)||list.find(n=>norm(n.name).includes(key)||key.includes(norm(n.name)))}
function segmentBlocked(s){return /CHẶN|KHÔNG DÙNG|TƯƠNG LAI/.test(`${s.status} ${s.role}`)}
function traceFor(id){return traces()[id]||null}
function edgeState(s){if(segmentBlocked(s))return{state:'BLOCKED_POLICY',reason:s.status};const t=traceFor(s.id);if(t?.status==='APPROVED_TRACE'&&Array.isArray(t.points)&&t.points.length>=2)return{state:'ACTIVE_TRACE',reason:`${t.points.length} điểm GPS`};if(t?.status==='FIELD_TRACE')return{state:'PENDING_TRACE_APPROVAL',reason:`${t.points?.length||0} điểm`};const a=nodeForName(s.from),b=nodeForName(s.to);if(a&&b)return{state:'NODE_GEOMETRY_READY',reason:'Đủ 2 nút, chưa có trace được duyệt'};if(a||b)return{state:'PARTIAL_GEOMETRY',reason:'Mới có 1 nút'};return{state:'PENDING_GEOMETRY',reason:'Thiếu geometry'}}
function routeState(r){const eligible=r.segments.filter(s=>!segmentBlocked(s)),states=eligible.map(edgeState),active=states.filter(x=>x.state==='ACTIVE_TRACE').length,ready=states.filter(x=>['ACTIVE_TRACE','NODE_GEOMETRY_READY'].includes(x.state)).length;let state='DRAFT';if(active===eligible.length&&eligible.length)state='ACTIVE';else if(active>0)state='PARTIAL_ACTIVE';else if(ready>0)state='GEOMETRY_READY';return{state,active,eligible:eligible.length,ready}}
function qaState(){const g=geomCounts(),eligible=routeData.routes.flatMap(r=>r.segments).filter(s=>!segmentBlocked(s)),active=eligible.filter(s=>edgeState(s).state==='ACTIVE_TRACE').length;return{qa005:g.approved===53?'PASS':g.approved>0?'PARTIAL':'BLOCKED',qa010:eligible.length&&active===eligible.length?'PASS':active>0?'PARTIAL':'BLOCKED',approved:g.approved,active,eligible:eligible.length}}
function metrics(){const s=routeData.summary,g=geomCounts(),q=qaState();return `<div class="metrics"><div class="metric"><b>${s.corridors??'—'}</b><small>HÀNH LANG</small></div><div class="metric"><b>${s.segments??'—'}</b><small>ĐOẠN</small></div><div class="metric"><b>${g.approved}/53</b><small>GEOMETRY DUYỆT</small></div><div class="metric"><b>${q.active}/${q.eligible}</b><small>TRACE ACTIVE</small></div><div class="metric"><b>${pois().length}</b><small>ĐIỂM THƯ VIỆN</small></div><div class="metric"><b>${q.qa010}</b><small>ROUTE ENGINE</small></div></div>`}
function tagState(s){return s==='ACTIVE_TRACE'||s==='APPROVED_GEOMETRY'||s==='ACTIVE'?'good':/BLOCKED|PENDING|DRAFT/.test(s)?'warn':''}
function renderRoutes(q=''){const list=routeData.routes.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q));$('main').innerHTML=`${traceSession?traceBanner():''}<h2>Mạng tuyến PDH Travel</h2>${metrics()}<div class="notice"><b>Route engine RC1.5:</b> cạnh chỉ ACTIVE khi segment có <b>APPROVED_TRACE</b>. Geometry 2 nút chỉ cho biết topology sẵn sàng, không được coi là lộ trình thực.</div><div class="grid">${list.map(r=>{const rs=routeState(r);return `<article class="panel route ${r.id===currentRouteId?'selected':''}" onclick="selectRoute('${r.id}')"><span class="tag">${r.id}</span><span class="tag ${tagState(rs.state)}">${rs.state}</span><h3>${r.name}</h3><div class="meta">${r.primary}<br>${rs.active}/${rs.eligible} đoạn có trace duyệt</div>${r.segments.map(s=>{const es=edgeState(s);return `<div class="seg"><div class="seghead"><b>${s.id} · ${s.from} → ${s.to}</b><span class="tag ${tagState(es.state)}">${es.state}</span></div><div class="meta">${s.road} · ${es.reason}</div><div class="actions">${!segmentBlocked(s)?`<button onclick="event.stopPropagation();startTrace('${r.id}','${s.id}')">▶ Ghi vệt</button>`:''}${session()?.role==='admin'&&traceFor(s.id)?.status==='FIELD_TRACE'?`<button onclick="event.stopPropagation();approveTrace('${s.id}')">✓ Duyệt trace</button>`:''}</div></div>`}).join('')}</article>`}).join('')}</div>`}
function renderGeometry(q=''){const list=mergedNodes().filter(n=>!q||`${n.id} ${n.name} ${n.status}`.toLowerCase().includes(q)),admin=session()?.role==='admin';$('main').innerHTML=`${traceSession?traceBanner():''}<h2>Geometry nút PDH <small>(${list.length}/53)</small></h2>${metrics()}<div class="notice">Bật GPS → tới đúng nút → Ghi GPS nút → Admin duyệt. Sai số >80 m không được ghi. Map-matching tự động chỉ ưu tiên trace/nút đã duyệt.</div><div class="grid">${list.map(n=>`<div class="panel"><span class="tag">${n.id}</span><span class="tag ${tagState(n.status)}">${n.status}</span><h3>${n.name}</h3><div class="meta">${Number.isFinite(n.lat)?`${n.lat.toFixed(6)}, ${n.lng.toFixed(6)} · ±${n.accuracy||'—'} m`:'Chưa có tọa độ'}</div><div class="actions"><button class="primary" onclick="captureNode('${n.id}')">⌖ Ghi GPS nút</button>${admin&&n.status==='FIELD_CAPTURED'?`<button onclick="approveNode('${n.id}')">✓ Duyệt</button>`:''}${admin&&n.status!=='PENDING_COORDINATE'?`<button onclick="resetNode('${n.id}')">Xóa</button>`:''}</div></div>`).join('')}</div>`}
function renderLibrary(q=''){const list=pois().filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)),r=routeById(currentRouteId);$('main').innerHTML=`<h2>Thư viện PDH</h2>${metrics()}<div class="actions"><button class="primary" onclick="openPoiForm()">+ Thêm địa điểm</button><button onclick="openShareImport()">Nhận link Google Maps</button></div><div class="notice">Tuyến đang chọn: <b>${r.id} · ${r.name}</b>. Điểm thủ công không tự xác minh; chỉ có tích xanh khi người nhập xác nhận tại chỗ.</div><div class="grid">${list.length?list.map(p=>`<div class="panel"><span class="tag">${p.category}</span>${p.verified?'<span class="tag good">✓ Đã xác nhận</span>':'<span class="tag warn">Chưa xác minh</span>'}<h3>${p.name}</h3><div class="meta">${p.subcategory||''}<br>${Number.isFinite(p.lat)?`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}`:'Chưa có tọa độ'}<br>Tuyến: ${p.routeId||'—'}</div><p>${p.note||''}</p>${p.image?`<img src="${p.image}" alt="" style="max-width:100%;border-radius:10px">`:''}</div>`).join(''):'<div class="panel">Chưa có địa điểm người dùng. Dữ liệu tuyến PDH vẫn hoạt động độc lập.</div>'}</div>`}
function renderAdmin(){const s=session();if(!s||s.role!=='admin'){$('main').innerHTML='<div class="panel"><h2>Admin</h2><p>Chưa đăng nhập Admin.</p><button class="pill" onclick="openAccount()">Đăng nhập / tạo Admin</button></div>';return}const q=qaState(),g=geomCounts(),a=auditLog();$('main').innerHTML=`<h2>Admin · Release & Data Gate</h2>${metrics()}<div class="panel"><div class="qa"><b>QA-005 · Geometry 53 nút</b><span class="tag ${q.qa005==='PASS'?'good':'warn'}">${q.qa005}</span></div><div class="qa"><b>QA-010 · Route engine liên tục</b><span class="tag ${q.qa010==='PASS'?'good':'warn'}">${q.qa010}</span></div><p class="meta">Approved geometry ${g.approved}/53 · Approved trace ${q.active}/${q.eligible}. Chỉ khi đủ dữ liệu thực mới PASS.</p><div class="actions"><button onclick="exportBackup()">Xuất backup JSON</button><button onclick="document.getElementById('importFile').click()">Nhập backup</button><input id="importFile" class="hidden" type="file" accept="application/json" onchange="importBackup(this.files[0])"><button class="danger" onclick="clearAudit()">Xóa audit</button></div></div><div class="panel"><h3>Audit log</h3>${a.slice(0,80).map(x=>`<div class="audit"><b>${x.action}</b> · ${x.target}<br>${new Date(x.at).toLocaleString('vi-VN')} · ${x.actor}</div>`).join('')||'<div class="meta">Chưa có audit.</div>'}</div>`}
function render(){const q=$('search').value.toLowerCase().trim();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(view==='routes')renderRoutes(q);else if(view==='geometry')renderGeometry(q);else if(view==='library')renderLibrary(q);else renderAdmin();updateHero()}
$('search').oninput=render;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='account')openAccount();else{view=b.dataset.nav;render()}});
function rad(x){return x*Math.PI/180}function distanceKm(a,b){const R=6371,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng),s=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(s)))}
function pointSegKm(p,a,b){const lat0=rad(p.lat),kx=111.320*Math.cos(lat0),ky=110.574,px=(p.lng-a.lng)*kx,py=(p.lat-a.lat)*ky,bx=(b.lng-a.lng)*kx,by=(b.lat-a.lat)*ky,den=bx*bx+by*by,t=den?Math.max(0,Math.min(1,(px*bx+py*by)/den)):0;return Math.hypot(px-t*bx,py-t*by)}
function distanceToTrace(f,t){let best=Infinity;const p=t.points||[];for(let i=0;i<p.length-1;i++)best=Math.min(best,pointSegKm(f,p[i],p[i+1]));return best}
function recognizeRoute(f){let candidates=[];for(const r of routeData.routes){for(const s of r.segments){const t=traceFor(s.id);if(t?.status==='APPROVED_TRACE'&&t.points?.length>=2){const d=distanceToTrace(f,t);candidates.push({route:r,segment:s,distance:d,source:'APPROVED_TRACE'})}}}candidates.sort((a,b)=>a.distance-b.distance);if(candidates.length){const best=candidates[0],second=candidates[1],margin=second?second.distance-best.distance:99;let confidence='THẤP';if(f.accuracy<=40&&best.distance<=0.2&&margin>=0.1)confidence='CAO';else if(f.accuracy<=80&&best.distance<=1)confidence='TRUNG BÌNH';return{...best,confidence,margin}}let nodeCandidates=[];for(const r of routeData.routes){for(const s of r.segments){const a=nodeForName(s.from),b=nodeForName(s.to);for(const n of [a,b].filter(Boolean)){const d=distanceKm(f,n);nodeCandidates.push({route:r,segment:s,distance:d,source:'APPROVED_NODE',node:n})}}}nodeCandidates.sort((a,b)=>a.distance-b.distance);if(!nodeCandidates[0])return null;return{...nodeCandidates[0],confidence:'THẤP',margin:0}}
function weightedFix(){if(!fixes.length)return null;let sw=0,lat=0,lng=0,acc=0;for(const f of fixes){const w=1/Math.max(25,f.accuracy*f.accuracy);sw+=w;lat+=f.lat*w;lng+=f.lng*w;acc+=f.accuracy*w}const n=fixes.at(-1);return{...n,lat:lat/sw,lng:lng/sw,accuracy:Math.round(acc/sw)}}
function acceptableFix(f){if(!Number.isFinite(f.lat)||!Number.isFinite(f.lng)||!Number.isFinite(f.accuracy)||f.accuracy>250)return false;if(lastAccepted){const dt=(f.at-lastAccepted.at)/1000;if(dt>0){const kph=distanceKm(lastAccepted,f)/dt*3600,reported=Number.isFinite(f.speed)&&f.speed>=0?f.speed*3.6:null;if(kph>250&&(reported===null||reported<180))return false}}return true}
function quality(a){return a<=25?'RẤT TỐT':a<=50?'TỐT':a<=100?'TRUNG BÌNH':'YẾU'}
function renderFix(f){lastFix=f;$('gpsStatus').textContent=`GPS: ${f.lat.toFixed(5)}, ${f.lng.toFixed(5)}`;$('gpsAccuracy').textContent=`±${f.accuracy} m · ${quality(f.accuracy)}`;$('gpsMotion').textContent=`Tốc độ: ${Number.isFinite(f.speed)&&f.speed>=0?Math.round(f.speed*3.6)+' km/h':'—'} · Hướng: ${Number.isFinite(f.heading)&&f.heading>=0?Math.round(f.heading)+'°':'—'}`;$('gpsAge').textContent=`Tuổi mẫu: ${Math.max(0,Math.round((Date.now()-f.at)/1000))}s`;const rr=recognizeRoute(f);if(!rr){$('routeDetect').innerHTML='Map matching: <b>chưa có geometry/trace được duyệt</b>.';return}const d=rr.distance<1?Math.round(rr.distance*1000)+' m':rr.distance.toFixed(1)+' km';$('routeDetect').innerHTML=`${rr.source==='APPROVED_TRACE'?'Đang khớp':'Ứng viên'}: <b>${rr.route.id} · ${rr.segment.id}</b><br>${d} · ${rr.source} · tin cậy <b>${rr.confidence}</b>`;if(rr.source==='APPROVED_TRACE'&&rr.confidence==='CAO'&&currentRouteId!==rr.route.id)selectRoute(rr.route.id,'approved-trace');write('d1-route-detection',{routeId:rr.route.id,segmentId:rr.segment.id,distanceKm:rr.distance,confidence:rr.confidence,source:rr.source,at:Date.now()})}
function appendTracePoint(f){if(!traceSession)return;const pts=traceSession.points,last=pts.at(-1);if(!last||distanceKm(last,f)>=0.01||f.at-last.at>=5000){pts.push({lat:f.lat,lng:f.lng,accuracy:f.accuracy,at:f.at});traceSession.lastAt=f.at;if(pts.length%10===0)render()}}
function onPosition(p){const f={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy||999,speed:p.coords.speed,heading:p.coords.heading,at:p.timestamp||Date.now()};if(!acceptableFix(f)){$('gpsAccuracy').textContent=`Mẫu loại · ±${Math.round(f.accuracy)} m`;return}lastAccepted=f;fixes.push(f);if(fixes.length>7)fixes.shift();const sm=weightedFix();write('d1-last-gps',sm);renderFix(sm);appendTracePoint(sm)}
function onErr(e){const m={1:'chưa cấp quyền vị trí',2:'không lấy được vị trí',3:'hết thời gian chờ'};$('gpsStatus').textContent=`GPS: ${m[e.code]||'lỗi '+e.code}`;$('gpsAccuracy').textContent='Kiểm tra quyền vị trí'}
function startGPS(){if(!navigator.geolocation){alert('Thiết bị không hỗ trợ Geolocation.');return}if(watchId!==null)navigator.geolocation.clearWatch(watchId);gpsActive=true;$('gpsBtn').classList.add('on');$('gpsStatus').textContent='GPS: đang lấy vị trí…';navigator.geolocation.getCurrentPosition(onPosition,()=>{},{enableHighAccuracy:false,timeout:5000,maximumAge:10000});watchId=navigator.geolocation.watchPosition(onPosition,onErr,{enableHighAccuracy:true,timeout:20000,maximumAge:0});if(navigator.vibrate)navigator.vibrate(25)}
$('gpsBtn').onclick=startGPS;
window.captureNode=id=>{if(!lastFix)return alert('Bật GPS và chờ vị trí trước.');if(lastFix.accuracy>80)return alert('Sai số GPS >80 m. Hãy chờ tín hiệu tốt hơn.');const ov=geometryLocal();ov[id]={lat:lastFix.lat,lng:lastFix.lng,accuracy:lastFix.accuracy,capturedAt:Date.now(),capturedBy:session()?.email||'local-loader',status:'FIELD_CAPTURED',approval:'PENDING_ADMIN_APPROVAL'};setGeometryLocal(ov);audit('NODE_CAPTURED',id,{accuracy:lastFix.accuracy});render()};
window.approveNode=id=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');const ov=geometryLocal();if(!ov[id])return;ov[id].status='APPROVED_GEOMETRY';ov[id].approval='APPROVED';ov[id].approvedAt=Date.now();ov[id].approvedBy=session().email;setGeometryLocal(ov);audit('NODE_APPROVED',id,{accuracy:ov[id].accuracy});render();if(lastFix)renderFix(lastFix)};
window.resetNode=id=>{if(session()?.role!=='admin')return;const ov=geometryLocal();delete ov[id];setGeometryLocal(ov);audit('NODE_RESET',id);render()};
window.startTrace=(routeId,segmentId)=>{if(segmentBlocked(routeById(routeId).segments.find(s=>s.id===segmentId)))return alert('Đoạn này bị chặn theo policy.');if(traceSession)return alert('Đang ghi một đoạn khác. Hãy dừng trước.');if(!gpsActive)startGPS();traceSession={routeId,segmentId,startedAt:Date.now(),points:[]};audit('TRACE_STARTED',segmentId,{routeId});render()};
function traceBanner(){return `<div class="traceon">● ĐANG GHI ${traceSession.segmentId} · ${traceSession.points.length} điểm <button class="btn" onclick="stopTrace()">Dừng & lưu</button> <button class="btn danger" onclick="cancelTrace()">Hủy</button></div>`}
window.stopTrace=()=>{if(!traceSession)return;const t=traces();if(traceSession.points.length<2)return alert('Chưa đủ điểm GPS để tạo trace.');t[traceSession.segmentId]={...traceSession,endedAt:Date.now(),status:'FIELD_TRACE',capturedBy:session()?.email||'local-loader'};setTraces(t);audit('TRACE_CAPTURED',traceSession.segmentId,{points:traceSession.points.length});traceSession=null;render()};
window.cancelTrace=()=>{if(traceSession)audit('TRACE_CANCELLED',traceSession.segmentId,{points:traceSession.points.length});traceSession=null;render()};
window.approveTrace=id=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');const t=traces();if(!t[id])return;t[id].status='APPROVED_TRACE';t[id].approvedAt=Date.now();t[id].approvedBy=session().email;setTraces(t);audit('TRACE_APPROVED',id,{points:t[id].points?.length||0});render();if(lastFix)renderFix(lastFix)};
window.openPoiForm=()=>{$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Thêm địa điểm</h2><input id="poiName" placeholder="Tên địa điểm"><select id="poiCategory"><option>Quán ăn</option><option>Coffee</option><option>Lưu trú</option><option>Trạm dừng</option><option>Cây xăng</option><option>Vui chơi</option><option>Tham quan</option><option>Tâm linh</option></select><input id="poiSub" placeholder="Phân loại phụ"><input id="poiNote" placeholder="Ghi chú"><input id="poiImage" type="file" accept="image/*"><label><input id="poiVerified" type="checkbox" style="width:auto"> Tôi đã kiểm chứng tại chỗ</label><div class="actions"><button class="primary" onclick="savePoi()">Lưu</button><button onclick="closeModal()">Hủy</button></div><p class="meta">Tọa độ sẽ lấy từ GPS hiện tại nếu đang có. Ảnh tối đa 700 KB để bảo vệ bộ nhớ cục bộ.</p></div></div>`};
window.savePoi=async()=>{const name=$('poiName').value.trim();if(!name)return alert('Nhập tên địa điểm.');let image=null,file=$('poiImage').files[0];if(file){if(file.size>700000)return alert('Ảnh vượt 700 KB.');image=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const p={id:'P-'+Date.now(),name,category:$('poiCategory').value,subcategory:$('poiSub').value.trim(),note:$('poiNote').value.trim(),verified:$('poiVerified').checked,lat:lastFix?.lat??null,lng:lastFix?.lng??null,accuracy:lastFix?.accuracy??null,routeId:currentRouteId,image,createdAt:Date.now(),createdBy:session()?.email||'local-user'};const list=pois();list.unshift(p);setPois(list);audit('POI_CREATED',p.id,{routeId:p.routeId,verified:p.verified});closeModal();view='library';render()};
function parseMapUrl(u){try{const d=decodeURIComponent(u);let m=d.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);if(!m)m=d.match(/!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)/);return m?{lat:+m[1],lng:+m[2]}:null}catch{return null}}
window.openShareImport=()=>{$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Nhận link Google Maps</h2><input id="mapUrl" placeholder="Dán link Google Maps đầy đủ"><input id="mapName" placeholder="Tên địa điểm"><button class="primary" onclick="saveMapLink()">Phân tích & lưu</button><p class="meta">Hỗ trợ link có @lat,lng hoặc !3dlat!4dlng. Link rút gọn cần mở ra URL đầy đủ trước.</p></div></div>`};
window.saveMapLink=()=>{const url=$('mapUrl').value.trim(),name=$('mapName').value.trim()||'Điểm chia sẻ Google Maps',c=parseMapUrl(url);if(!c)return alert('Không tìm thấy tọa độ trong link này. Hãy dùng URL đầy đủ.');const list=pois(),p={id:'P-'+Date.now(),name,category:'Chia sẻ Maps',subcategory:'Google Maps',note:url,verified:false,lat:c.lat,lng:c.lng,accuracy:null,routeId:currentRouteId,createdAt:Date.now(),createdBy:session()?.email||'local-user'};list.unshift(p);setPois(list);audit('MAP_LINK_IMPORTED',p.id,{lat:c.lat,lng:c.lng});closeModal();view='library';render()};
function backupObject(){return{schema:1,appVersion:APP_VERSION,createdAt:Date.now(),geometry:geometryLocal(),traces:traces(),pois:pois(),audit:auditLog()}}
window.exportBackup=()=>{const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PDH-D1-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);audit('BACKUP_EXPORTED','local')};
window.importBackup=async file=>{if(session()?.role!=='admin')return alert('Cần quyền Admin.');if(!file)return;try{const data=JSON.parse(await file.text());if(data.schema!==1)throw new Error('Sai schema');if(data.geometry)write('d1-geometry-overrides',data.geometry);if(data.traces)write('d1-segment-traces',data.traces);if(data.pois)write('d1-pois',data.pois);if(Array.isArray(data.audit))write('d1-audit',data.audit.slice(0,500));audit('BACKUP_IMPORTED',file.name);render()}catch(e){alert('Backup không hợp lệ: '+e.message)}};
window.clearAudit=()=>{if(session()?.role!=='admin')return;if(confirm('Xóa audit log cục bộ?')){write('d1-audit',[]);audit('AUDIT_RESET','local');render()}};
async function hash(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
window.openAccount=()=>{const s=session();$('modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>Tài khoản</h2>${s?`<p><b>${s.email}</b> · ${s.role}</p><div class="actions"><button onclick="logout()">Đăng xuất</button></div>`:`<input id="email" type="email" placeholder="Email"><input id="pass" type="password" placeholder="Mật khẩu"><div class="actions"><button class="primary" onclick="login()">Đăng nhập</button><button onclick="createUser()">Tạo User</button><button onclick="createAdmin()">Tạo Admin đầu tiên</button></div>`}<p class="meta">RC1.5 vẫn là tài khoản cục bộ để kiểm thử RBAC. Chưa phải backend authentication đa thiết bị.</p></div></div>`};
window.closeModal=()=>{$('modal').innerHTML=''};
window.createUser=async()=>{const email=$('email').value.trim().toLowerCase(),pass=$('pass').value;if(!email||pass.length<6)return alert('Email hợp lệ, mật khẩu ≥6 ký tự.');let u=users();if(u.some(x=>x.email===email))return alert('Email đã tồn tại.');u.push({email,passHash:await hash(pass),role:'user'});setUsers(u);setSession({email,role:'user'});audit('USER_CREATED',email);closeModal();render()};
window.createAdmin=async()=>{const email=$('email').value.trim().toLowerCase(),pass=$('pass').value;if(!email||pass.length<6)return alert('Email hợp lệ, mật khẩu ≥6 ký tự.');let u=users();if(u.some(x=>x.role==='admin'))return alert('Thiết bị đã có Admin.');u.push({email,passHash:await hash(pass),role:'admin'});setUsers(u);setSession({email,role:'admin'});audit('ADMIN_CREATED',email);closeModal();render()};
window.login=async()=>{const email=$('email').value.trim().toLowerCase(),ph=await hash($('pass').value),u=users().find(x=>x.email===email&&x.passHash===ph);if(!u)return alert('Sai tài khoản/mật khẩu.');setSession({email:u.email,role:u.role});audit('LOGIN',email,{role:u.role});closeModal();render()};
window.logout=()=>{audit('LOGOUT',session()?.email||'local');setSession(null);closeModal();render()};$('accountBtn').onclick=openAccount;
async function permissionState(){try{if(!navigator.permissions)return;const s=await navigator.permissions.query({name:'geolocation'});if(s.state==='denied'){$('gpsStatus').textContent='GPS: quyền vị trí đang bị chặn';$('gpsAccuracy').textContent='Mở quyền vị trí trong trình duyệt'}}catch{}}
async function boot(){syncInstall();permissionState();try{const [r,g]=await Promise.all([fetch(`data/routes-pdh.json?v=${DATA_VERSION}`,{cache:'reload'}),fetch(`data/geometry-pdh.json?v=${GEOMETRY_VERSION}`,{cache:'reload'})]);if(!r.ok||!g.ok)throw new Error('HTTP dữ liệu');routeData=await r.json();geometryBase=await g.json();if(routeData.version!==DATA_VERSION||geometryBase.version!==GEOMETRY_VERSION)throw new Error('Sai version dữ liệu');if(!routeData.routes.some(x=>x.id===currentRouteId))currentRouteId='R-001';const cached=read('d1-last-gps',null);if(cached&&Date.now()-cached.at<3600000)renderFix(cached);render()}catch(e){$('main').innerHTML=`<div class="panel badbox"><h2>Lỗi nạp dữ liệu</h2><p>${e.message}</p></div>`}}
boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');