const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const services={RouteStore:{getSelectedId:()=>localStorage.getItem('d1-route')||'R-A'},GeometryStore:{overrides:()=>({N1:{lat:10,lng:106,status:'APPROVED_GEOMETRY'},N2:{lat:10.1,lng:106,status:'APPROVED_GEOMETRY'}}),traces:()=>({S1:{status:'APPROVED_TRACE',points:[{lat:10,lng:106},{lat:10.1,lng:106}]}})}};
const context={console,Math,Number,String,Array,JSON,localStorage,window:null,DiDauServices:services,routeData:{routes:[{id:'R-A',name:'A',segments:[{id:'S1',from:'Node 1',to:'Node 2',status:'READY',role:'PRIMARY'}]},{id:'R-B',name:'B',segments:[{id:'S2',from:'Node 2',to:'Node 3',status:'READY',role:'PRIMARY'}]}],summary:{}},geometryBase:{nodes:[{id:'N1',name:'Node 1'},{id:'N2',name:'Node 2'},{id:'N3',name:'Node 3'}],summary:{}}};
context.window=context;
vm.createContext(context);
vm.runInContext(fs.readFileSync('rc2-route-geometry-domain-v3.js','utf8'),context,{filename:'rc2-route-geometry-domain-v3.js'});
const D=context.DiDauRouteGeometry;
assert.equal(D.version,'3.2.0-rc2');
assert.equal(D.RouteDomain.byId('R-B').id,'R-B');
assert.equal(D.RouteDomain.selected().id,'R-A');
assert.equal(D.GeometryDomain.counts().approved,2);
assert.equal(D.GeometryDomain.edgeState(context.routeData.routes[0].segments[0]).state,'ACTIVE_TRACE');
assert.equal(D.RouteDomain.state(context.routeData.routes[0]).state,'ACTIVE');
assert.equal(D.RouteDomain.qa().qa010,'PARTIAL');
const match=D.GeometryDomain.recognizeRoute({lat:10.05,lng:106,accuracy:20});
assert(match);assert.equal(match.route.id,'R-A');assert.equal(match.source,'APPROVED_TRACE');
localStorage.setItem('d1-route','R-B');assert.equal(D.RouteDomain.selected().id,'R-B');
console.log('CORE V3 PHASE3 ROUTE/GEOMETRY DOMAIN: PASS');
