const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('rc2-ui-shell-v3.js','utf8');
const boot=fs.readFileSync('rc2-bootstrap-v3.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const gradle=fs.readFileSync('android/app/build.gradle','utf8');
assert(html.includes('rc2-ui-shell-v3.js'));
assert(html.includes('rc2-bootstrap-v3.js'));
assert(html.indexOf('rc2-unified-driving-ui.js')<html.indexOf('rc2-ui-shell-v3.js'));
assert(html.indexOf('rc2-ui-shell-v3.js')<html.indexOf('rc2-bootstrap-v3.js'));
assert(ui.includes("version:'3.3.0-rc2'"));
assert(ui.includes('DiDauUiShell'));
assert(ui.includes('renderRoutes'));
assert(ui.includes('renderGeometry'));
assert(ui.includes('renderLibrary'));
assert(ui.includes('renderAdmin'));
assert(ui.includes('DiDauRouteGeometry'));
assert(ui.includes('DiDauServices'));
assert(!ui.includes("routeId==='R-002'"));
assert(!ui.includes('localStorage.'));
assert(boot.includes("version:'3.3.0-rc2'"));
assert(boot.includes('DiDauBootstrap'));
assert(boot.includes("dataset.bootstrap='core-v3'"));
assert(!boot.includes('R-002'));
assert(sw.includes("'./rc2-ui-shell-v3.js'"));
assert(sw.includes("'./rc2-bootstrap-v3.js'"));
assert(gradle.includes("include 'rc2-ui-shell-v3.js'"));
assert(gradle.includes("include 'rc2-bootstrap-v3.js'"));
console.log('CORE V3 PHASE4 UI/BOOTSTRAP OWNERSHIP: PASS');
