const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),clear:()=>store.clear()};
const context={console,Math,JSON,Number,String,Boolean,Date,localStorage,window:null,currentRouteId:undefined,routeData:{routes:[{id:'R-001',name:'One'},{id:'R-002',name:'Two'}]},routeById:id=>context.routeData.routes.find(r=>r.id===id),lastFix:null,getGpsHealth:null};
context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync('rc2-app-services-v3.js','utf8'),context,{filename:'rc2-app-services-v3.js'});
const S=context.DiDauServices;
assert(S);assert.equal(S.version,'3.1.0-rc2');
S.RouteStore.setSelectedId('R-002','test');assert.equal(S.RouteStore.getSelectedId(),'R-002');assert.equal(S.RouteStore.getSource(),'test');
S.AccountStore.setUsers([{email:'a@test',role:'admin'}]);assert.equal(S.AccountStore.users().length,1);
S.AccountStore.setSession({email:'a@test',role:'admin'});assert.equal(S.AccountStore.session().role,'admin');
S.PoiStore.setAll([{id:'p1',routeId:'R-002',lat:10,lng:106,gpsRankEligible:true},{id:'p2',routeId:'R-001',lat:11,lng:106,gpsRankEligible:true}]);assert.equal(S.PoiStore.count(),2);
S.AuditStore.append('TEST','phase2');assert.equal(S.AuditStore.all()[0].actor,'a@test');
S.GpsStore.setLast({lat:10,lng:106,speed:0,heading:null});assert.equal(S.GpsStore.last().lat,10);
vm.runInContext(fs.readFileSync('rc2-engine-v3.js','utf8'),context,{filename:'rc2-engine-v3.js'});
const E=context.DiDauEngine;assert(E);assert.equal(E.version,'3.1.0-rc2');
assert.equal(E.RouteContext.getRouteId(),'R-002');
const eligible=E.PoiRepository.eligible({routeId:'R-002'});assert.equal(eligible.length,1);assert.equal(eligible[0].id,'p1');
assert.equal(E.GpsService.fix().lat,10);
S.RouteStore.setSelectedId('R-001','test');assert.equal(E.RouteContext.getRouteId(),'R-001');assert.equal(E.PoiRepository.eligible({routeId:E.RouteContext.getRouteId()})[0].id,'p2');
console.log('CORE V3 PHASE2 SERVICES: PASS');
